# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='applying_as_a',
            field=models.CharField(choices=[('ME', 'Merchant'), ('US', 'User')], default='US', max_length=2),
        ),
    ]
