# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bundles', models.IntegerField(default=10)),
                ('bundles_used', models.IntegerField(default=0)),
                ('top_left_coordinate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('top_right_coordinate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bottom_left_coordinate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bottom_right_coordinate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.zone'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.slot'),
        ),
    ]
