# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0002_zone_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='bottom_left_coordinate',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='bottom_right_coordinate',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='top_left_coordinate',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='top_right_coordinate',
        ),
        migrations.AddField(
            model_name='zone',
            name='bottom_left_coordinate_x',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='zone',
            name='bottom_left_coordinate_y',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
